package com.fiap.challenge.InvestmentDataService.client.brapi_dto;

public record BalanceSheetStatement(
        String type,
        String endDate,
        Long cash,
        Long propertyPlantEquipment,
        Long totalAssets,
        Long totalLiab,
        Long commonStock,
        Object treasuryStock, // Pode ser null, então Object é mais flexível
        Long otherStockholderEquity,
        Long totalStockholderEquity,
        Object netTangibleAssets, // Pode ser null
        Object goodWill, // Pode ser null
        Long intangibleAssets,
        Object deferredLongTermAssetCharges, // Pode ser null
        Object capitalSurplus, // Pode ser null
        Long financialAssets,
        Long centralBankCompulsoryDeposit,
        Long financialAssetsMeasuredAtFairValueThroughProfitOrLoss,
        Long currentAndDeferredTaxes,
        Long investments,
        Long financialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome,
        Long financialAssetsAtAmortizedCost,
        Long financialLiabilitiesMeasuredAtFairValueThroughIncome,
        Long financialLiabilitiesAtAmortizedCost,
        Long provisions,
        Long taxLiabilities,
        Long otherLiabilities,
        Long shareholdersEquity,
        Long controllerShareholdersEquity,
        Long nonControllingShareholdersEquity,
        Long realizedShareCapital,
        Long capitalReserves,
        Long profitReserves,
        Object accumulatedProfitsOrLosses, // Pode ser null
        Long otherComprehensiveResults,
        String updatedAt,
        Long shortTermInvestments,
        Long netReceivables,
        Long inventory,
        Long otherCurrentAssets,
        Long totalCurrentAssets,
        Long longTermInvestments,
        Long otherAssets,
        Long accountsPayable,
        Long shortLongTermDebt,
        Long longTermDebt,
        Long otherLiab,
        Long totalCurrentLiabilities,
        Object retainedEarnings,
        Long deferredLongTermLiab,
        Long minorityInterest,
        Long accountsReceivableFromClients,
        Long otherAccountsReceivable,
        Long taxesToRecover,
        Long prepaidExpenses,
        Long longTermAssets,
        Long longTermRealizableAssets,
        Long longTermDeferredTaxes,
        Long longTermPrepaidExpenses,
        Object shareholdings, // Pode ser Object devido à inconsistência do JSON
        Long otherNonCurrentAssets,
        Long nonCurrentAssets,
        Long currentLiabilities,
        Long socialAndLaborObligations,
        Long providers,
        Long nationalSuppliers,
        Long foreignSuppliers,
        Long taxObligations,
        Long loansAndFinancing,
        Long loansAndFinancingInNationalCurrency,
        Long loansAndFinancingInForeignCurrency,
        Long otherObligations,
        Long nonCurrentLiabilities,
        Long longTermLoansAndFinancing,
        Long longTermLoansAndFinancingInNationalCurrency,
        Long longTermLoansAndFinancingInForeignCurrency,
        Long longTermDebentures,
        Long otherLongTermObligations,
        Long longTermProvisions,
        Object revaluationReserves,
        Long equityValuationAdjustments,
        Object longTermBiologicalAssets,
        Object creditsWithRelatedParties
) {}
