name: CI - Develop

on:
    push:
        branches: ["develop"]
    pull_request:
        branches: ["develop"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build InvestmentDataService
              run: docker build ./InvestmentDataService

            - name: Build ProfileAnalyzerService
              run: docker build ./ProfileAnalyzerService

            - name: Build RecommenderService
              run: docker build ./RecommenderService
